
skillMetadata:
  sections:
    - name: Settings 
      fields:
        - name: portnum
          type: number
          label: Portumber
          value: "3000"
        - name: auto_start
          type: checkbox
          label: Start VSCode-server when device starts
          value: "True"
    - name: Security
      fields:
        - name: token
          type: password
          label: Security Token
          value: "1234"
